import type { AgentId, AITask } from "../types";

export type AgentPolicy = {
  id: AgentId;
  purpose: string;
  allowedTasks: AITask[];
  restrictedTasks: AITask[];
  moderationHooks: string[];
  escalationHooks: string[];
  analyticsHooks: string[];
  timeoutMs: number;
  costAwareness: "low" | "medium" | "high";
  knowledgeSources: string[];
};

const policies: Record<AgentId, AgentPolicy> = {
  StrategyAgent: {
    id: "StrategyAgent",
    purpose: "Campaign strategy, offer framing, audience angle, and goal selection",
    allowedTasks: ["copywriting", "classification", "chat"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["no_fake_claims", "compliance_marketing_claims"],
    escalationHooks: ["medium_confidence", "professional_review"],
    analyticsHooks: ["strategy_generation"],
    timeoutMs: 20_000,
    costAwareness: "high",
    knowledgeSources: ["campaign_templates", "seasonal_campaign_knowledge", "brand_voice_rules"],
  },
  CopyAgent: {
    id: "CopyAgent",
    purpose: "Hooks, captions, email copy, scripts, CTAs, and platform-native wording",
    allowedTasks: ["copywriting", "chat"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["compliance_marketing_claims"],
    escalationHooks: ["medium_confidence"],
    analyticsHooks: ["copy_generation"],
    timeoutMs: 20_000,
    costAwareness: "medium",
    knowledgeSources: ["social_templates", "cta_templates", "brand_voice_rules"],
  },
  CreativeDirectorAgent: {
    id: "CreativeDirectorAgent",
    purpose: "Visual direction, shot lists, image prompts, video briefs, and presenter direction",
    allowedTasks: ["copywriting", "text_to_image", "text_to_video", "image_edit", "avatar_video", "text_to_speech"],
    restrictedTasks: [],
    moderationHooks: ["media_safety", "impersonation_check"],
    escalationHooks: ["medium_confidence", "professional_review"],
    analyticsHooks: ["creative_direction"],
    timeoutMs: 30_000,
    costAwareness: "high",
    knowledgeSources: ["brand_voice_rules", "social_templates", "safety_compliance_rules"],
  },
  PlatformIntelligenceAgent: {
    id: "PlatformIntelligenceAgent",
    purpose: "Platform fit, format constraints, channel recommendations, and draft-mode limitations",
    allowedTasks: ["classification", "copywriting", "chat"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["autopublish_guard"],
    escalationHooks: ["medium_confidence"],
    analyticsHooks: ["platform_fit"],
    timeoutMs: 15_000,
    costAwareness: "low",
    knowledgeSources: ["social_templates", "campaign_templates"],
  },
  GrowthAgent: {
    id: "GrowthAgent",
    purpose: "Marketing strategy, messaging, and growth orchestration",
    allowedTasks: ["copywriting", "classification", "chat", "embeddings"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["compliance_marketing_claims"],
    escalationHooks: ["professional_review"],
    analyticsHooks: ["campaign_generation"],
    timeoutMs: 20_000,
    costAwareness: "high",
    knowledgeSources: ["campaign_templates", "cta_templates", "seasonal_campaign_knowledge"],
  },
  MediaAgent: {
    id: "MediaAgent",
    purpose: "Media generation and queue-safe asset production",
    allowedTasks: ["text_to_image", "image_edit", "image_to_video", "text_to_video", "avatar_video", "text_to_speech", "speech_to_text", "image_captioning"],
    restrictedTasks: [],
    moderationHooks: ["media_safety", "impersonation_check"],
    escalationHooks: ["medium_confidence", "high_confidence"],
    analyticsHooks: ["media_generation"],
    timeoutMs: 120_000,
    costAwareness: "high",
    knowledgeSources: ["brand_voice_rules", "social_templates"],
  },
  SchedulerAgent: {
    id: "SchedulerAgent",
    purpose: "Approval-first scheduling recommendations and launch calendar planning",
    allowedTasks: ["classification", "copywriting", "chat"],
    restrictedTasks: ["avatar_video", "text_to_video"],
    moderationHooks: ["autopublish_guard"],
    escalationHooks: ["medium_confidence"],
    analyticsHooks: ["schedule_recommendations"],
    timeoutMs: 15_000,
    costAwareness: "low",
    knowledgeSources: ["launch_templates", "seasonal_campaign_knowledge"],
  },
  LearningAgent: {
    id: "LearningAgent",
    purpose: "Feedback capture, rejected-draft learning notes, and improvement hints",
    allowedTasks: ["classification", "copywriting", "chat", "embeddings"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["privacy_guard", "no_fake_claims"],
    escalationHooks: ["medium_confidence"],
    analyticsHooks: ["learning_loop"],
    timeoutMs: 15_000,
    costAwareness: "low",
    knowledgeSources: ["brand_voice_rules", "campaign_templates"],
  },
  AnalyticsAgent: {
    id: "AnalyticsAgent",
    purpose: "Campaign performance analysis, growth scoring, and optimization recommendations",
    allowedTasks: ["classification", "copywriting", "chat", "embeddings"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["privacy_guard", "no_fake_claims"],
    escalationHooks: ["medium_confidence"],
    analyticsHooks: ["campaign_performance"],
    timeoutMs: 15_000,
    costAwareness: "low",
    knowledgeSources: ["campaign_templates", "seasonal_campaign_knowledge"],
  },
  AudienceAgent: {
    id: "AudienceAgent",
    purpose: "Audience segmentation, suppression-safe targeting, and engagement recommendations",
    allowedTasks: ["classification", "copywriting", "chat", "embeddings"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["privacy_guard", "gdpr_guard"],
    escalationHooks: ["medium_confidence"],
    analyticsHooks: ["audience_targeting"],
    timeoutMs: 15_000,
    costAwareness: "medium",
    knowledgeSources: ["campaign_templates", "brand_voice_rules"],
  },
  StableAssistantAgent: {
    id: "StableAssistantAgent",
    purpose: "Stable operations assistant and rider support",
    allowedTasks: ["chat", "classification", "copywriting", "moderation"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["unsafe_riding_guard"],
    escalationHooks: ["professional_review"],
    analyticsHooks: ["assistant_support"],
    timeoutMs: 25_000,
    costAwareness: "medium",
    knowledgeSources: ["stable_management_knowledge", "uk_equestrian_terminology", "safety_compliance_rules"],
  },
  AcademyAgent: {
    id: "AcademyAgent",
    purpose: "Education and academy-oriented AI guidance",
    allowedTasks: ["chat", "copywriting", "classification", "moderation"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["academy_safety_guard"],
    escalationHooks: ["professional_review"],
    analyticsHooks: ["academy_ai_usage"],
    timeoutMs: 25_000,
    costAwareness: "medium",
    knowledgeSources: ["onboarding_templates", "safety_compliance_rules"],
  },
  CustomerSuccessAgent: {
    id: "CustomerSuccessAgent",
    purpose: "Onboarding, lifecycle communication, and retention messaging",
    allowedTasks: ["chat", "copywriting", "classification", "text_to_speech"],
    restrictedTasks: ["avatar_video"],
    moderationHooks: ["no_fake_claims"],
    escalationHooks: ["medium_confidence"],
    analyticsHooks: ["onboarding_ai_usage"],
    timeoutMs: 20_000,
    costAwareness: "medium",
    knowledgeSources: ["onboarding_templates", "launch_templates", "cta_templates"],
  },
  ComplianceAgent: {
    id: "ComplianceAgent",
    purpose: "Policy moderation, claims safety, and escalation routing",
    allowedTasks: ["moderation", "classification", "chat"],
    restrictedTasks: ["text_to_video", "avatar_video"],
    moderationHooks: ["gdpr_guard", "medical_claim_guard", "endorsement_guard", "autopublish_guard"],
    escalationHooks: ["low_confidence", "medium_confidence", "high_confidence", "professional_review"],
    analyticsHooks: ["compliance_events"],
    timeoutMs: 15_000,
    costAwareness: "low",
    knowledgeSources: ["safety_compliance_rules"],
  },
  AdminOpsAgent: {
    id: "AdminOpsAgent",
    purpose: "System diagnostics, orchestration visibility, and operations support",
    allowedTasks: ["chat", "classification", "moderation", "embeddings"],
    restrictedTasks: [],
    moderationHooks: ["admin_guardrails"],
    escalationHooks: ["medium_confidence"],
    analyticsHooks: ["ops_diagnostics"],
    timeoutMs: 20_000,
    costAwareness: "high",
    knowledgeSources: ["launch_templates", "brand_voice_rules"],
  },
};

export function getAgentPolicy(id: AgentId): AgentPolicy {
  return policies[id];
}

export function listAgentPolicies(): AgentPolicy[] {
  return Object.values(policies);
}
